name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t ci-media-ots .

    - name: Run Pylint
      run: docker run --rm -v $PWD:/src ci-media-ots pylint $(git ls-files '*.py')